import type { Metadata } from "next";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Terms of Service — Regulatory Framework & Compliance",
  description: "Review Avenix Pharmaceuticals' Terms of Service. Compliance directives under the Drugs and Cosmetics Act, 1940, doctor-patient guidelines, and booking rules.",
  keywords: ["Avenix terms of service", "pharmacy compliance india", "healthcare teleconsulting rules"],
};

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="flex-grow bg-white py-12 sm:py-16 md:py-20 text-left">
        <div className="mx-auto max-w-[1200px] px-4 sm:px-6 lg:px-8 space-y-10">
          
          <div className="border-b border-gray-150 pb-6 space-y-2">
            <span className="text-[10px] font-black text-[#FF6B00] uppercase tracking-widest">Regulatory Framework</span>
            <h1 className="text-3xl sm:text-4xl font-black text-[#0F2C59] tracking-tight">Terms of Service</h1>
            <p className="text-xs text-gray-400 font-bold">Last Updated: May 26, 2026</p>
          </div>

          <div className="space-y-8 text-xs sm:text-sm text-gray-500 font-semibold leading-relaxed">
            <div className="space-y-3">
              <h2 className="text-lg font-black text-gray-900">1. Drugs and Cosmetics Act Compliance</h2>
              <p>
                Avenix Pharmaceuticals operates fully in accordance with the Drugs and Cosmetics Act, 1940 and the Drugs and Cosmetics Rules, 1945. Scheduled prescription drugs (Schedule H, H1, or X) will strictly not be dispatched without valid prescription upload and verification by our certified registered pharmacists.
              </p>
            </div>

            <div className="space-y-3">
              <h2 className="text-lg font-black text-gray-900">2. Teleconsultation & Diagnostics Limits</h2>
              <p>
                Video consultations hosted via the Avenix Doctor Consultation desk connect users with independent, licensed doctors registered under the National Medical Commission (NMC). Telehealth consultations do not replace in-person hospital visits for life-critical medical emergencies. Diagnostics packages booked on our platform are processed by accredited NABL pathology laboratories.
              </p>
            </div>

            <div className="space-y-3">
              <h2 className="text-lg font-black text-gray-900">3. Electronic Account Portals</h2>
              <p>
                Users logged in to the Avenix portal are responsible for safeguarding their dynamic email login profiles. Any automated credential verification downloads or printable billing invoices generated by our dashboard portal remain secure electronic statements signed under the Information Technology Act, 2000.
              </p>
            </div>

            <div className="space-y-3">
              <h2 className="text-lg font-black text-gray-900">4. Gateway Terms</h2>
              <p>
                All digital transactions are routed securely via official payment processors like Razorpay. Order checkouts are verified and dispatched under strict CDSCO temperature-controlled warehouse regulations to ensure product safety.
              </p>
            </div>
          </div>

        </div>
      </main>
      <Footer />
    </>
  );
}
